name: GKE Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/hello-world-service:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/hello-world-service:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl set image deployment/hello-world hello-world=gcr.io/${{ secrets.GCP_PROJECT }}/hello-world-service:$GITHUB_SHA

