name: Docker build and Deploy

on:
  push:
    branches: [master]

jobs:
  create-image-and-push-to-gcr:

    name: Create Image and Push to GCR
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: us-central1-docker.pkg.dev/my-demo-project-434216/my-demo-registry/hello_world:${{ github.sha }}

  setup-and-deploy:
    needs: [create-image-and-push-to-gcr]

    name: Setup and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}

    - name: Update Image Tag in Deployment
      run: |-
        sed -i -e "s|us-central1-docker.pkg.dev/my-demo-project-434216/my-demo-registry/hello-world|us-central1-docker.pkg.dev/my-demo-project-434216/my-demo-registry/hello_world:${{ github.sha }}|" ./kubernetes/deploy.yaml

    - name: Apply Deployment to GKE
      run: |
        kubectl apply -f ./kubernetes/

    - name: Force Deployment Rollout
      run: kubectl rollout restart deployment.apps/hello-world-deployment
